import type { TableData } from '../types/table';

export const generateFakeTableData = (): TableData => {
  return [
    {
      owner: 'Yossi Cohen',
      floorCount: '21–40',
      status: 'In progress',
      startDate: '2025-06-01',
      dueDate: '2025-06-15',
      requiresManagerApproval: true,
      taskType: 'Inspection',
      priority: 'High',
    },
    {
      owner: 'Sarah Levi',
      floorCount: '1–20',
      status: 'Todo',
      startDate: '2025-06-05',
      dueDate: '2025-06-20',
      requiresManagerApproval: false,
      taskType: 'Execution',
      priority: 'Medium',
    },
    {
      owner: 'David Azulay',
      floorCount: '41+',
      status: 'On hold',
      startDate: '2025-05-25',
      dueDate: '2025-06-10',
      requiresManagerApproval: true,
      taskType: 'Execution',
      priority: 'High',
    },
    {
      owner: 'Rachel Green',
      floorCount: '21–40',
      status: 'In progress',
      startDate: '2025-06-01',
      dueDate: '2025-06-30',
      requiresManagerApproval: false,
      taskType: 'Planning',
      priority: 'Low',
    },
    {
      owner: 'Michael Brown',
      floorCount: '1–20',
      status: 'Done',
      startDate: '2025-05-01',
      dueDate: '2025-05-15',
      requiresManagerApproval: true,
      taskType: 'Inspection',
      priority: 'Medium',
    },
    {
      owner: 'Emily White',
      floorCount: '41+',
      status: 'Todo',
      startDate: '2025-06-10',
      dueDate: '2025-06-25',
      requiresManagerApproval: false,
      taskType: 'Execution',
      priority: 'High',
    },
    {
      owner: 'Daniel Black',
      floorCount: '1–20',
      status: 'In progress',
      startDate: '2025-05-20',
      dueDate: '2025-06-05',
      requiresManagerApproval: true,
      taskType: 'Planning',
      priority: 'Low',
    },
    {
      owner: 'Olivia Gray',
      floorCount: '21–40',
      status: 'On hold',
      startDate: '2025-05-15',
      dueDate: '2025-05-30',
      requiresManagerApproval: false,
      taskType: 'Maintenance',
      priority: 'Medium',
    },
    {
      owner: 'Ethan Gold',
      floorCount: '41+',
      status: 'In progress',
      startDate: '2025-06-01',
      dueDate: '2025-06-20',
      requiresManagerApproval: true,
      taskType: 'Execution',
      priority: 'High',
    },
    {
      owner: 'Sophia Silver',
      floorCount: '21–40',
      status: 'Todo',
      startDate: '2025-06-05',
      dueDate: '2025-06-25',
      requiresManagerApproval: false,
      taskType: 'Inspection',
      priority: 'Medium',
    },
    {
      owner: 'Liam Copper',
      floorCount: '1–20',
      status: 'Done',
      startDate: '2025-05-01',
      dueDate: '2025-05-15',
      requiresManagerApproval: true,
      taskType: 'Maintenance',
      priority: 'Low',
    },
    {
      owner: 'Ava Bronze',
      floorCount: '41+',
      status: 'On hold',
      startDate: '2025-05-20',
      dueDate: '2025-06-05',
      requiresManagerApproval: false,
      taskType: 'Execution',
      priority: 'High',
    },
    {
      owner: 'Noah Steel',
      floorCount: '21–40',
      status: 'In progress',
      startDate: '2025-06-01',
      dueDate: '2025-06-15',
      requiresManagerApproval: true,
      taskType: 'Planning',
      priority: 'Medium',
    },
    {
      owner: 'Isabella Platinum',
      floorCount: '1–20',
      status: 'Todo',
      startDate: '2025-06-10',
      dueDate: '2025-06-25',
      requiresManagerApproval: false,
      taskType: 'Execution',
      priority: 'Low',
    },
    {
      owner: 'James Diamond',
      floorCount: '41+',
      status: 'Done',
      startDate: '2025-05-01',
      dueDate: '2025-05-15',
      requiresManagerApproval: true,
      taskType: 'Inspection',
      priority: 'High',
    },
  ];
};